apiVersion: 1

datasources:
  - name: "Prometheus"
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: GET